# Generated by Django 5.0.3 on 2024-04-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=80)),
                ('fecha_fin', models.DateField()),
                ('responsable', models.CharField(max_length=50)),
            ],
        ),
    ]
